---
permalink: deploy/concept-migration-of-disaster-recovery-setup-from-windows-to-appliance.html 
sidebar: sidebar 
keywords: migration, windows, SRM, appliance, 
summary: 'Se você estiver usando o Gerenciador de recuperação de site (SRM) baseado no Windows para recuperação de desastres e quiser usar o utilitário SRM para a mesma configuração, então você deve migrar sua configuração de recuperação de desastres do Windows para o SRM baseado no dispositivo.' 
---
= Migração do Windows SRM para o dispositivo SRM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver usando o Gerenciador de recuperação de site (SRM) baseado no Windows para recuperação de desastres e quiser usar o utilitário SRM para a mesma configuração, então você deve migrar sua configuração de recuperação de desastres do Windows para o SRM baseado no dispositivo.

As etapas envolvidas na migração da recuperação de desastres são:

. Atualizando seu dispositivo virtual existente para VSC, VSA Provider e SRA para a versão 9.7.1.
+
link:task-upgrade-to-the-9-7-1-virtual-appliance-for-vsc-vasa-provider-and-sra.html["Atualize para o dispositivo virtual 9.7.1 para VSC, VSA Provider e SRA"^]

. Migração do adaptador de replicação de armazenamento baseado no Windows para o SRA baseado em appliance.
. Migração de dados do Windows SRM para o dispositivo SRM.


https://docs.vmware.com/en/Site-Recovery-Manager/8.2/com.vmware.srm.install_config.doc/GUID-F39A84D3-2E3D-4018-97DD-5D7F7E041B43.html["Clique aqui"^] para obter passos detalhados.
