---
permalink: deploy/task-clean-the-vsphere-cached-downloaded-plug-in-packages.html 
sidebar: sidebar 
keywords: clean, up, browser, cache, cleaning, the, vsphere, cached, downloaded, plug-in, packages, 
summary: Se os plug-ins não forem atualizados automaticamente após a implantação ou atualização do dispositivo virtual para VSC, provedor VASA e SRA, você deverá limpar os pacotes de plug-in de download em cache no navegador e no vCenter Serverpara resolver problemas de plug-in do vCenter Server. 
---
= Limpe os pacotes de plug-in baixados em cache do vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se os plug-ins não forem atualizados automaticamente após a implantação ou atualização do dispositivo virtual para VSC, provedor VASA e SRA, você deverá limpar os pacotes de plug-in de download em cache no navegador e no vCenter Server para resolver problemas de plug-in do vCenter Server.

.Passos
. Efetue logout do seu cliente da Web vSphere ou do vSphere Client existente.
. Remova o cache do navegador.
. Remova os pacotes de plug-in armazenados em cache do vSphere Client.
+
[cols="1a,1a"]
|===
| Se você estiver usando... | Execute o seguinte... 


 a| 
Servidor Windows vCenter
 a| 
Remova as seguintes pastas com.NetApp.vasa.vvol.webclient-x.x.xxxx, com.NetApp.nvpf.webclient-x.x.xxxx e com.NetApp.vsch5-x.x.x.xxxx localizadas em:

** Caminho do vSphere Web Client: C
** Caminho do vSphere Client(HTML5): C




 a| 
VCSA
 a| 
.. SSH no dispositivo VCSA.
.. Altere os diretórios para o diretório de extensões de IU do vCenter Web client usando `cd /etc/vmware/vsphere-client/vc-packages/vsphere-client-serenity`
.. Remova os pacotes de plugins armazenados em cache usando os comandos:
+
*** `rm -rf com.netapp.vasa.vvol.webclient-x.x.x.xxxx`
*** `rm -rf com.netapp.nvpf.webclient-x.x.x.xxxx`
*** `rm -rf com.netapp.vsch5-x.x.x.xxxx`


.. Mude os diretórios para o diretório de extensões de IU do vCenter client(HTML5) usando `cd /etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity`
.. Remova os pacotes de plugins armazenados em cache usando os comandos:
+
*** `rm -rf com.netapp.vasa.vvol.webclient-x.x.x.xxxx`
*** `rm -rf com.netapp.nvpf.webclient-x.x.x.xxxx`
*** `rm -rf com.netapp.vsch5-x.x.x.xxxx`




|===
. Faça login no vSphere e reinicie os serviços do vSphere Web Client e do vSphere Client usando os seguintes comandos:
+
** `service-control --stop vsphere-client vsphere-ui`
** `service-control --start vsphere-client vsphere-ui`



