---
permalink: deploy/task-set-default-credentials-for-storage-systems.html 
sidebar: sidebar 
keywords: setting, default, credentials, storage, systems, 
summary: Você pode usar o Virtual Storage Console para VMware vSphere para definir credenciais padrão para um sistema de storage no vCenter Server. 
---
= Definir credenciais padrão para sistemas de storage
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o Virtual Storage Console para VMware vSphere para definir credenciais padrão para um sistema de storage no vCenter Server.

.Antes de começar
Você deve ter selecionado o vCenter Server que deseja usar para criar credenciais padrão.

.Sobre esta tarefa
Se você configurar credenciais padrão para sistemas de storage, o VSC usará essas credenciais para fazer login em um sistema de storage que o VSC acabou de descobrir. Se as credenciais padrão não funcionarem, você deverá fazer login manualmente no sistema de storage. O VSC e o SRA oferecem suporte à adição de credenciais do sistema de storage no nível do cluster ou no nível. Mas o provedor VASA só funcionará com credenciais de cluster.

.Passos
. Na página VSC *Home*, clique em menu:Configurações[Configurações administrativas > Configurar credenciais padrão para o sistema de armazenamento].
. Na caixa de diálogo *credenciais predefinidas do sistema de armazenamento*, introduza o nome de utilizador e a palavra-passe do sistema de armazenamento.
+
As credenciais do controlador de armazenamento são atribuídas no ONTAP com base no nome de utilizador e no par de palavras-passe. As credenciais do controlador de storage podem ser a conta de administrador ou uma conta personalizada que usa o controle de acesso baseado em funções (RBAC).

+
Não é possível usar o VSC para alterar as funções associadas ao nome de usuário e ao par de senhas do controlador de armazenamento. Para modificar ou criar uma nova função de usuário do ONTAP para uso com o dispositivo virtual para VSC, provedor VASA e SRA, você pode usar o Gerenciador do sistema.

+
Consulte a seção ""Configurando funções de usuário e Privileges"" no _Console de armazenamento virtual, provedor VASA e adaptador de replicação de armazenamento para VMware vSphere Deployment and Setup Guide for 9,7 Release_.

. Clique em *OK* para salvar as credenciais padrão.


.Depois de terminar
Se você atualizou as credenciais do sistema de armazenamento porque um sistema de armazenamento relatou o status de "Falha de autenticação", clique na opção *REDESCOBRIR TUDO* disponível na página sistemas de armazenamento. Ao fazer isso, o VSC tenta se conetar ao sistema de storage usando as novas credenciais.
