---
permalink: manage/concept-considerations-for-creating-and-editing-storage-capability-profiles.html 
sidebar: sidebar 
keywords: considerations, for, creating, and, editing, storage, capability, profiles, 
summary: Você deve estar ciente das considerações para criar e editar perfis de capacidade de armazenamento. 
---
= Considerações para criar e editar perfis de capacidade de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente das considerações para criar e editar perfis de capacidade de armazenamento.

* Você pode configurar IOPS mínimo somente em sistemas AFF.
* Você pode configurar métricas de QoS em um nível de armazenamento de dados de volume virtual (VVol).
+
Esse recurso oferece maior flexibilidade na atribuição de métricas de QoS variadas para VMDKs diferentes da mesma máquina virtual provisionada em um datastore virtual.

* Você pode configurar perfis de capacidade de storage para armazenamentos de dados FAS e AFF.
+
Para sistemas FAS, você pode configurar a reserva de espaço para ser espessa ou fina, mas para sistemas AFF, a reserva de espaço só pode ser configurada como thin.

* Você pode usar perfis de capacidade de storage para fornecer criptografia para seus datastores.
* Não é possível modificar os perfis de capacidade de armazenamento existentes após a atualização de uma versão anterior do dispositivo virtual para Virtual Storage Console (VSC), Fornecedor VASA e adaptador de replicação de armazenamento (SRA) para a versão mais recente do dispositivo virtual para VSC, Fornecedor VASA e SRA.
+
Os perfis de capacidade de armazenamento legados são retidos para compatibilidade com versões anteriores. Se os modelos padrão não estiverem em uso, durante a atualização para a versão mais recente do dispositivo virtual para VSC, Fornecedor VASA e SRA, os modelos existentes serão substituídos para refletir as novas métricas de QoS relacionadas ao desempenho dos perfis de capacidade de armazenamento.

* Não é possível modificar ou usar os perfis de funcionalidades de storage herdados para provisionar novos armazenamentos de dados virtuais ou políticas de storage de VM.
* Você deve usar novos perfis de funcionalidades de storage para todos os novos datastores.

